protocols = imap
listen = *
ssl = no
disable_plaintext_auth = no
mail_location = maildir:/mail/%d/%n
first_valid_uid = 0
mail_plugins = quota

plugin {
  quota = maildir:User quota
  quota_rule = *:storage=1G
}

protocol imap {
  mail_plugins = $mail_plugins imap_quota
}

passdb {
  driver = passwd-file
  args = /etc/dovecot/passwd
}
userdb {
  driver = passwd-file
  args = /etc/dovecot/passwd
}

service imap-login {
  inet_listener imap {
    port = 143
  }
}

log_path = /dev/stderr
info_log_path = /dev/stdout
