dovecot_config_version = 2.4.1
dovecot_storage_version = 2.4.1
protocols = imap lmtp
listen = 0.0.0.0
base_dir = /run/dovecot
state_dir = /var/lib/gotth-mail/mail/.state
log_path = /dev/stderr
info_log_path = /dev/stdout
mail_uid = 1000
mail_gid = 1000
mail_home = /var/lib/gotth-mail/mail/%{user | domain}/%{user | username}
mail_driver = maildir
mail_path = ~/Maildir
auth_mechanisms = plain login
auth_allow_cleartext = yes
auth_verbose = no
auth_debug = no
auth_debug_passwords = no
haproxy_trusted_networks = 127.0.0.1/32 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16
passdb static {
  fields {
    nopassword = yes
  }
}
userdb static {
  fields {
    uid = 1000
    gid = 1000
    home = /var/lib/gotth-mail/mail/%{user | domain}/%{user | username}
  }
}
service imap-login {
  inet_listener imap {
    port = 143
    haproxy = yes
  }
}
service lmtp {
  inet_listener lmtp {
    port = 24
  }
}
service auth {
  inet_listener auth-postfix {
    port = 12345
  }
}
mail_plugins {
  quota = yes
}
protocol imap {
  mail_plugins {
    imap_quota = yes
  }
}
protocol lmtp {
  mail_plugins {
    sieve = yes
  }
}
quota "User quota" {
}
sieve_script personal {
  path = ~/.dovecot.sieve
}
ssl = no
