load_module /usr/lib/nginx/modules/ngx_mail_module.so;

worker_processes 1;
pid /tmp/nginx.pid;
error_log stderr notice;

events {
    worker_connections 1024;
}

mail {
    server_name mail;
    auth_http http://control-plane:8080/internal/v1/front/auth;
    auth_http_header X-GOTTH-Mail-Front-Token @GOTTH_MAIL_FRONT_AUTH_TOKEN@;
    proxy on;
    proxy_protocol on;
    xclient off;
    proxy_timeout 24h;
    proxy_pass_error_message on;
    ssl_certificate /run/gotth-mail/tls/certificate.pem;
    ssl_certificate_key /run/gotth-mail/tls/private-key.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_session_cache shared:MAIL:10m;

    server {
        listen 1025;
        protocol smtp;
        smtp_auth none;
        starttls on;
    }

    server {
        listen 1465 ssl;
        protocol smtp;
        smtp_auth plain login;
        proxy_smtp_auth on;
    }

    server {
        listen 1587;
        protocol smtp;
        smtp_auth plain login;
        proxy_smtp_auth on;
        starttls only;
    }

    server {
        listen 1143;
        protocol imap;
        imap_auth plain login;
        starttls only;
    }

    server {
        listen 1993 ssl;
        protocol imap;
        imap_auth plain login;
    }
}
