package render

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"forgejo/linus/gophermailforge/internal/config"
)

type File struct{ Path, Content string }
type Set struct {
	ID    string
	Files []File
}

const Header = "# Generated by GopherMailForge. Do not edit directly. Use configured override paths.\n"
const CurrentFile = "current"

func Render(c config.Config) Set {
	files := []File{{"control-plane.conf", fmt.Sprintf("public_url=%s\nlisten=%s\ntls_mode=%s\nauthentik=%s\n", c.Server.PublicURL, c.Server.Listen, c.TLS.Mode, c.Authentik.BaseURL)}}
	for _, p := range c.Plugins {
		files = append(files, File{Path: "plugins/" + p.Name + ".conf", Content: fmt.Sprintf("name=%s\nseam=%s\nendpoint=%s\n", p.Name, p.Seam, p.Endpoint)})
	}
	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })
	h := sha256.New()
	for i := range files {
		files[i].Content = Header + files[i].Content
		h.Write([]byte(files[i].Path))
		h.Write([]byte{0})
		h.Write([]byte(files[i].Content))
	}
	return Set{ID: hex.EncodeToString(h.Sum(nil))[:16], Files: files}
}

func Write(dir string, s Set) error {
	root := filepath.Join(dir, s.ID)
	for _, f := range s.Files {
		p := filepath.Join(root, filepath.Clean(f.Path))
		if !strings.HasPrefix(p, root+string(os.PathSeparator)) {
			return fmt.Errorf("unsafe render path %q", f.Path)
		}
		if err := os.MkdirAll(filepath.Dir(p), 0755); err != nil {
			return err
		}
		if err := os.WriteFile(p, []byte(f.Content), 0644); err != nil {
			return err
		}
	}
	return nil
}

func Read(dir, id string) (Set, error) {
	if id == "" || strings.Contains(id, string(os.PathSeparator)) || id == "." || id == ".." {
		return Set{}, fmt.Errorf("invalid render id %q", id)
	}
	root := filepath.Join(dir, id)
	var files []File
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		b, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		files = append(files, File{Path: filepath.ToSlash(rel), Content: string(b)})
		return nil
	})
	if err != nil {
		return Set{}, err
	}
	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })
	return Set{ID: id, Files: files}, nil
}

func ReadCurrent(appliedDir string) (Set, error) {
	b, err := os.ReadFile(filepath.Join(appliedDir, CurrentFile))
	if os.IsNotExist(err) {
		return Set{}, nil
	}
	if err != nil {
		return Set{}, err
	}
	id := strings.TrimSpace(string(b))
	return Read(appliedDir, id)
}

func MarkApplied(appliedDir string, s Set) error {
	if err := Write(appliedDir, s); err != nil {
		return err
	}
	tmp := filepath.Join(appliedDir, CurrentFile+".tmp")
	if err := os.WriteFile(tmp, []byte(s.ID+"\n"), 0644); err != nil {
		return err
	}
	return os.Rename(tmp, filepath.Join(appliedDir, CurrentFile))
}

func Diff(a, b Set) []string {
	m := map[string]string{}
	for _, f := range a.Files {
		m[f.Path] = f.Content
	}
	out := []string{}
	for _, f := range b.Files {
		if old, ok := m[f.Path]; !ok {
			out = append(out, "add "+f.Path)
		} else if old != f.Content {
			out = append(out, "change "+f.Path)
		}
		delete(m, f.Path)
	}
	for p := range m {
		out = append(out, "delete "+p)
	}
	sort.Strings(out)
	if len(out) == 0 {
		return []string{"no changes"}
	}
	return out
}
func HashText(s string) string   { h := sha256.Sum256([]byte(s)); return hex.EncodeToString(h[:]) }
func JoinDiff(d []string) string { return strings.Join(d, "\n") }
