package render

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"forgejo/linus/gophermailforge/internal/config"
)

type File struct{ Path, Content string }
type Set struct {
	ID    string
	Files []File
}

const Header = "# Generated by GopherMailForge. Do not edit directly. Use configured override paths.\n"

func Render(c config.Config) Set {
	files := []File{{"control-plane.conf", fmt.Sprintf("public_url=%s\nlisten=%s\ntls_mode=%s\nauthentik=%s\n", c.Server.PublicURL, c.Server.Listen, c.TLS.Mode, c.Authentik.BaseURL)}}
	for _, p := range c.Plugins {
		files = append(files, File{Path: "plugins/" + p.Name + ".conf", Content: fmt.Sprintf("name=%s\nseam=%s\nendpoint=%s\n", p.Name, p.Seam, p.Endpoint)})
	}
	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })
	h := sha256.New()
	for i := range files {
		files[i].Content = Header + files[i].Content
		h.Write([]byte(files[i].Path))
		h.Write([]byte{0})
		h.Write([]byte(files[i].Content))
	}
	return Set{ID: hex.EncodeToString(h.Sum(nil))[:16], Files: files}
}
func Write(dir string, s Set) error {
	root := filepath.Join(dir, s.ID)
	for _, f := range s.Files {
		p := filepath.Join(root, f.Path)
		if err := os.MkdirAll(filepath.Dir(p), 0755); err != nil {
			return err
		}
		if err := os.WriteFile(p, []byte(f.Content), 0644); err != nil {
			return err
		}
	}
	return nil
}
func Diff(a, b Set) []string {
	m := map[string]string{}
	for _, f := range a.Files {
		m[f.Path] = f.Content
	}
	out := []string{}
	for _, f := range b.Files {
		if old, ok := m[f.Path]; !ok {
			out = append(out, "add "+f.Path)
		} else if old != f.Content {
			out = append(out, "change "+f.Path)
		}
		delete(m, f.Path)
	}
	for p := range m {
		out = append(out, "delete "+p)
	}
	sort.Strings(out)
	if len(out) == 0 {
		return []string{"no changes"}
	}
	return out
}
func HashText(s string) string   { h := sha256.Sum256([]byte(s)); return hex.EncodeToString(h[:]) }
func JoinDiff(d []string) string { return strings.Join(d, "\n") }
