package render

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"forgejo/gotthboard/gotth-mail/internal/config"
)

type File struct{ Path, Content string }
type Set struct {
	ID        string
	InputHash string
	Files     []File
}

const Header = "# Generated by GOTTH Mail. Do not edit directly.\n"
const CurrentFile = "current"

func Render(c config.Config) Set {
	files := []File{{"control-plane.conf", fmt.Sprintf("public_url=%s\nlisten=%s\ntls_mode=%s\nauthentik=%s\n", c.Server.PublicURL, c.Server.Listen, c.TLS.Mode, c.Authentik.BaseURL)}}
	for _, p := range c.Plugins {
		files = append(files, File{Path: "plugins/" + p.Name + ".conf", Content: fmt.Sprintf("name=%s\nseam=%s\nendpoint=%s\n", p.Name, p.Seam, p.Endpoint)})
	}
	files = append(files, daemonConfigFiles(c)...)
	return finalize(files, inputHash(c))
}

func daemonConfigFiles(c config.Config) []File {
	api := strings.TrimRight(c.Server.PublicURL, "/")
	if api == "" {
		api = "http://gotth-mail:8080"
	}
	return []File{
		{Path: "front/nginx.conf", Content: fmt.Sprintf("server {\n  listen 80;\n  location /.well-known/acme-challenge/ { proxy_pass %s/internal/v1/acme/; }\n  location / { proxy_pass %s; }\n}\n", api, api)},
		{Path: "postfix/gotth-mail.conf", Content: fmt.Sprintf("gotth_mail_api_base = %s/internal/v1/postfix\ngotth_mail_domain_lookup = ${gotth_mail_api_base}/domains/{domain}\ngotth_mail_recipient_lookup = ${gotth_mail_api_base}/recipients/{address}\ngotth_mail_mailbox_lookup = ${gotth_mail_api_base}/mailboxes/{address}\ngotth_mail_alias_lookup = ${gotth_mail_api_base}/aliases/{address}\ngotth_mail_sender_login = ${gotth_mail_api_base}/sender-login\ngotth_mail_sender_policy = ${gotth_mail_api_base}/sender-policy\ngotth_mail_rate_limit = ${gotth_mail_api_base}/rate-limit/{sender}\ngotth_mail_transport = ${gotth_mail_api_base}/transport/{domain}\n", api)},
		{Path: "dovecot/gotth-mail.conf", Content: fmt.Sprintf("gotth_mail_api_base = %s/internal/v1/dovecot\ngotth_mail_passdb = ${gotth_mail_api_base}/passdb\ngotth_mail_userdb = ${gotth_mail_api_base}/userdb/{address}\ngotth_mail_quota = ${gotth_mail_api_base}/quota\ngotth_mail_default_sieve = ${gotth_mail_api_base}/sieve/default/{address}\n", api)},
		{Path: "rspamd/gotth-mail.conf", Content: fmt.Sprintf("gotth_mail_api_base = %s/internal/v1/rspamd\ngotth_mail_local_domains = ${gotth_mail_api_base}/local-domains\ngotth_mail_dkim = ${gotth_mail_api_base}/dkim/{domain}\ngotth_mail_signing_decision = ${gotth_mail_api_base}/signing-decision\ngotth_mail_rate_signal = ${gotth_mail_api_base}/rate-signal\n", api)},
		{Path: "webmail/provider.conf", Content: "provider=external\nhealth=plugin\n"},
	}
}

func finalize(files []File, inHash string) Set {
	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })
	bodyHash := sha256.New()
	for _, f := range files {
		bodyHash.Write([]byte(f.Path))
		bodyHash.Write([]byte{0})
		bodyHash.Write([]byte(f.Content))
	}
	id := hex.EncodeToString(bodyHash.Sum(nil))[:16]
	for i := range files {
		files[i].Content = Header + fmt.Sprintf("# Source: generated_config_set=%s input_hash=%s\n", id, inHash) + files[i].Content
	}
	return Set{ID: id, InputHash: inHash, Files: files}
}

func inputHash(c config.Config) string {
	h := sha256.New()
	h.Write([]byte(c.Server.PublicURL))
	h.Write([]byte{0})
	h.Write([]byte(c.Server.Listen))
	h.Write([]byte{0})
	h.Write([]byte(c.TLS.Mode))
	h.Write([]byte{0})
	h.Write([]byte(c.Authentik.BaseURL))
	plugins := append([]config.Plugin(nil), c.Plugins...)
	sort.Slice(plugins, func(i, j int) bool { return plugins[i].Name < plugins[j].Name })
	for _, p := range plugins {
		h.Write([]byte{0})
		h.Write([]byte(p.Name + "|" + p.Seam + "|" + p.Endpoint + "|" + p.Image))
	}
	return hex.EncodeToString(h.Sum(nil))
}

func Write(dir string, s Set) error {
	root := filepath.Join(dir, s.ID)
	for _, f := range s.Files {
		p := filepath.Join(root, filepath.Clean(f.Path))
		if !strings.HasPrefix(p, root+string(os.PathSeparator)) {
			return fmt.Errorf("unsafe render path %q", f.Path)
		}
		if err := os.MkdirAll(filepath.Dir(p), 0755); err != nil {
			return err
		}
		if err := os.WriteFile(p, []byte(f.Content), 0644); err != nil {
			return err
		}
	}
	return nil
}

func Read(dir, id string) (Set, error) {
	if id == "" || strings.Contains(id, string(os.PathSeparator)) || id == "." || id == ".." {
		return Set{}, fmt.Errorf("invalid render id %q", id)
	}
	root := filepath.Join(dir, id)
	var files []File
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		b, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		files = append(files, File{Path: filepath.ToSlash(rel), Content: string(b)})
		return nil
	})
	if err != nil {
		return Set{}, err
	}
	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })
	return Set{ID: id, Files: files}, nil
}

func ReadCurrent(appliedDir string) (Set, error) {
	b, err := os.ReadFile(filepath.Join(appliedDir, CurrentFile))
	if os.IsNotExist(err) {
		return Set{}, nil
	}
	if err != nil {
		return Set{}, err
	}
	id := strings.TrimSpace(string(b))
	return Read(appliedDir, id)
}

func MarkApplied(appliedDir string, s Set) error {
	if err := Write(appliedDir, s); err != nil {
		return err
	}
	tmp := filepath.Join(appliedDir, CurrentFile+".tmp")
	if err := os.WriteFile(tmp, []byte(s.ID+"\n"), 0644); err != nil {
		return err
	}
	return os.Rename(tmp, filepath.Join(appliedDir, CurrentFile))
}

func Diff(a, b Set) []string {
	m := map[string]string{}
	for _, f := range a.Files {
		m[f.Path] = f.Content
	}
	out := []string{}
	for _, f := range b.Files {
		if old, ok := m[f.Path]; !ok {
			out = append(out, "add "+f.Path)
		} else if old != f.Content {
			out = append(out, "change "+f.Path)
		}
		delete(m, f.Path)
	}
	for p := range m {
		out = append(out, "delete "+p)
	}
	sort.Strings(out)
	if len(out) == 0 {
		return []string{"no changes"}
	}
	return out
}
func HashText(s string) string   { h := sha256.Sum256([]byte(s)); return hex.EncodeToString(h[:]) }
func JoinDiff(d []string) string { return strings.Join(d, "\n") }
