// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/gotth/mail/plugin/v1/plugin.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginControl_Health_FullMethodName       = "/gotth.mail.plugin.v1.PluginControl/Health"
	PluginControl_Version_FullMethodName      = "/gotth.mail.plugin.v1.PluginControl/Version"
	PluginControl_Capabilities_FullMethodName = "/gotth.mail.plugin.v1.PluginControl/Capabilities"
)

// PluginControlClient is the client API for PluginControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginControlClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
	Capabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error)
}

type pluginControlClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginControlClient(cc grpc.ClientConnInterface) PluginControlClient {
	return &pluginControlClient{cc}
}

func (c *pluginControlClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, PluginControl_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginControlClient) Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, PluginControl_Version_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginControlClient) Capabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilitiesResponse)
	err := c.cc.Invoke(ctx, PluginControl_Capabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginControlServer is the server API for PluginControl service.
// All implementations must embed UnimplementedPluginControlServer
// for forward compatibility.
type PluginControlServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	Version(context.Context, *VersionRequest) (*VersionResponse, error)
	Capabilities(context.Context, *CapabilitiesRequest) (*CapabilitiesResponse, error)
	mustEmbedUnimplementedPluginControlServer()
}

// UnimplementedPluginControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginControlServer struct{}

func (UnimplementedPluginControlServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedPluginControlServer) Version(context.Context, *VersionRequest) (*VersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedPluginControlServer) Capabilities(context.Context, *CapabilitiesRequest) (*CapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Capabilities not implemented")
}
func (UnimplementedPluginControlServer) mustEmbedUnimplementedPluginControlServer() {}
func (UnimplementedPluginControlServer) testEmbeddedByValue()                       {}

// UnsafePluginControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginControlServer will
// result in compilation errors.
type UnsafePluginControlServer interface {
	mustEmbedUnimplementedPluginControlServer()
}

func RegisterPluginControlServer(s grpc.ServiceRegistrar, srv PluginControlServer) {
	// If the following call panics, it indicates UnimplementedPluginControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginControl_ServiceDesc, srv)
}

func _PluginControl_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginControlServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginControl_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginControlServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginControl_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginControlServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginControl_Version_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginControlServer).Version(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginControl_Capabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginControlServer).Capabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginControl_Capabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginControlServer).Capabilities(ctx, req.(*CapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginControl_ServiceDesc is the grpc.ServiceDesc for PluginControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gotth.mail.plugin.v1.PluginControl",
	HandlerType: (*PluginControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _PluginControl_Health_Handler,
		},
		{
			MethodName: "Version",
			Handler:    _PluginControl_Version_Handler,
		},
		{
			MethodName: "Capabilities",
			Handler:    _PluginControl_Capabilities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/gotth/mail/plugin/v1/plugin.proto",
}

const (
	NotificationBackend_SendAlert_FullMethodName  = "/gotth.mail.plugin.v1.NotificationBackend/SendAlert"
	NotificationBackend_SendPrompt_FullMethodName = "/gotth.mail.plugin.v1.NotificationBackend/SendPrompt"
)

// NotificationBackendClient is the client API for NotificationBackend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationBackendClient interface {
	SendAlert(ctx context.Context, in *SendAlertRequest, opts ...grpc.CallOption) (*DeliveryResponse, error)
	SendPrompt(ctx context.Context, in *SendPromptRequest, opts ...grpc.CallOption) (*PromptResponse, error)
}

type notificationBackendClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationBackendClient(cc grpc.ClientConnInterface) NotificationBackendClient {
	return &notificationBackendClient{cc}
}

func (c *notificationBackendClient) SendAlert(ctx context.Context, in *SendAlertRequest, opts ...grpc.CallOption) (*DeliveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryResponse)
	err := c.cc.Invoke(ctx, NotificationBackend_SendAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationBackendClient) SendPrompt(ctx context.Context, in *SendPromptRequest, opts ...grpc.CallOption) (*PromptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromptResponse)
	err := c.cc.Invoke(ctx, NotificationBackend_SendPrompt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationBackendServer is the server API for NotificationBackend service.
// All implementations must embed UnimplementedNotificationBackendServer
// for forward compatibility.
type NotificationBackendServer interface {
	SendAlert(context.Context, *SendAlertRequest) (*DeliveryResponse, error)
	SendPrompt(context.Context, *SendPromptRequest) (*PromptResponse, error)
	mustEmbedUnimplementedNotificationBackendServer()
}

// UnimplementedNotificationBackendServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificationBackendServer struct{}

func (UnimplementedNotificationBackendServer) SendAlert(context.Context, *SendAlertRequest) (*DeliveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendAlert not implemented")
}
func (UnimplementedNotificationBackendServer) SendPrompt(context.Context, *SendPromptRequest) (*PromptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendPrompt not implemented")
}
func (UnimplementedNotificationBackendServer) mustEmbedUnimplementedNotificationBackendServer() {}
func (UnimplementedNotificationBackendServer) testEmbeddedByValue()                             {}

// UnsafeNotificationBackendServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationBackendServer will
// result in compilation errors.
type UnsafeNotificationBackendServer interface {
	mustEmbedUnimplementedNotificationBackendServer()
}

func RegisterNotificationBackendServer(s grpc.ServiceRegistrar, srv NotificationBackendServer) {
	// If the following call panics, it indicates UnimplementedNotificationBackendServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotificationBackend_ServiceDesc, srv)
}

func _NotificationBackend_SendAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationBackendServer).SendAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationBackend_SendAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationBackendServer).SendAlert(ctx, req.(*SendAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationBackend_SendPrompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPromptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationBackendServer).SendPrompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationBackend_SendPrompt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationBackendServer).SendPrompt(ctx, req.(*SendPromptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationBackend_ServiceDesc is the grpc.ServiceDesc for NotificationBackend service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationBackend_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gotth.mail.plugin.v1.NotificationBackend",
	HandlerType: (*NotificationBackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendAlert",
			Handler:    _NotificationBackend_SendAlert_Handler,
		},
		{
			MethodName: "SendPrompt",
			Handler:    _NotificationBackend_SendPrompt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/gotth/mail/plugin/v1/plugin.proto",
}
